name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Greetings
        run: echo " Hello World :) "
      - name: Printing Current Working Directory
        run: pwd
      - name: listing directory
        run: ls -ltr
      - name: Printing Goodbye
        run: echo " Bye Bye user :) "
        
        
